version: '3.7'
services:
  product_listing:
    restart: always
    build:
      context: .
      dockerfile: ./product_listing/Dockerfile
      target: product-listing-builder
    container_name: "product_listing"
    ports:
      - "4000:3000"
    volumes:
      - ./product_listing/src:/code/src
      - ./product_listing/test:/code/test
      - ./product_listing/package.json:/code/package.json
      - ./product_listing/package-lock.json:/code/package-lock.json
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=user
      - DB_PWD=password
      - DB_DIALECT=postgres
      - DB_NAME=database
      - DISCOUNT_CALCULATOR_HOST=discount_calculator
      - DISCOUNT_CALCULATOR_PORT=50051
    depends_on:
      - db
  discount_calculator:
    restart: always
    build: 
      context: .
      dockerfile: ./discount_calculator/Dockerfile
      target: discount-calculator-builder
    container_name: "discount_calculator"
    volumes:
      - ./discount_calculator/src:/code/src
      - ./discount_calculator/test:/code/test
      - ./discount_calculator/Pipfile:/code/Pipfile
      - ./discount_calculator/Pipfile.lock:/code/Pipfile.lock
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PWD=password
      - DB_DIALECT=postgres
      - DB_NAME=database
      - GRPC_SERVER_PORT=50051
    depends_on:
      - db
  db:
    restart: always
    build: ./db
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
      - PGPASSWORD=password
